version: '3'

services:
  db:
    image: postgres
    restart: always
  web:
    build: myproject
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./myproject:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always